// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzPjfhbD4p_DXq6kQ2Y04je3auOVs34U4',
    appId: '1:9598128146:web:bfbae299a89e8e175a08cb',
    messagingSenderId: '9598128146',
    projectId: 'mobilvize-d1a10',
    authDomain: 'mobilvize-d1a10.firebaseapp.com',
    storageBucket: 'mobilvize-d1a10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZUFnCrwSJHqVH6PTW_sgao2PSHPXZl5s',
    appId: '1:9598128146:android:f8a21221aecf07d25a08cb',
    messagingSenderId: '9598128146',
    projectId: 'mobilvize-d1a10',
    storageBucket: 'mobilvize-d1a10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKq7e23zzsilLOxvJSB-8SWaIUzP3CGqw',
    appId: '1:9598128146:ios:e356c7558ed5e94e5a08cb',
    messagingSenderId: '9598128146',
    projectId: 'mobilvize-d1a10',
    storageBucket: 'mobilvize-d1a10.appspot.com',
    iosBundleId: 'com.example.mobilvize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKq7e23zzsilLOxvJSB-8SWaIUzP3CGqw',
    appId: '1:9598128146:ios:018141c8220196865a08cb',
    messagingSenderId: '9598128146',
    projectId: 'mobilvize-d1a10',
    storageBucket: 'mobilvize-d1a10.appspot.com',
    iosBundleId: 'com.example.mobilvize.RunnerTests',
  );
}
